#!/usr/bin/env python
#
# Splat - splat/tools/splat
#
# Copyright (C) 2015, 2016 Guillaume Tucker <guillaume@mangoz.org>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

def print_help():
    print("splat CMD")
    for cmd in COMMANDS.iterkeys():
        print("* {}".format(cmd))

def cmd_version(argv):
    import splat
    print(splat.VERSION_STR)

def cmd_help(argv):
    print_help()

def cmd_compare(argv):
    import splat.tools.compare
    splat.tools.compare.main(argv)

def find_commands():
    commands = {}
    for name, attr in globals().iteritems():
        if name.startswith('cmd_') and hasattr(attr, '__call__'):
            cmd = name.split('_')[1]
            commands[cmd] = attr
    return commands

COMMANDS = find_commands()

def main(argv):
    if len(argv) < 2:
        print_help()
        return True

    cmd_name = argv[1]
    cmd_func = COMMANDS.get(cmd_name, None)
    if cmd_func is None:
        print_help()
        return False
    else:
        cmd_func(argv[1:])
        return True

if __name__ == '__main__':
    res = main(sys.argv)
    sys.exit(0 if res is True else 1)
